### ISSUE TITLE
jinjar as enhancement to sqltargets

### ISSUE THREAD

**Issue by daranzolin** [davidchall/jinjar#38]
Hi David, 

Thanks for creating and maintaining this great package! It was precisely what I was looking for when I first discovered 'Jinja-like' SQL and hoped to implement its capabilities within the sqltargets package.

[I have an open pull request to add jinjar](https://github.com/daranzolin/sqltargets/pull/15) and it's passed some basic tests and checks. Before I merge, however, I would welcome your expertise on how to make the most of jinjar and how to implement it correctly. No worries if you're too busy, I still wanted to take the opportunity to thank you for this package.

**Comment by davidchall** [comment]
Hi @daranzolin, Thanks for your interest in jinjar - I'm so glad to hear you've found it helpful!

I took a quick look at your PR and have a couple of comments:
1. Query parameters are passed to `jinjar::render()` as a single named list object `params`. As a result, template variables require a namespace. For example, `{{ params.payment_methods }}` instead of `{{ payment_methods }}`. If this was unintentional, you should be able to use the slice operator to access the parameters directly. <img width="585" alt="image" src="https://github.com/user-attachments/assets/58535af2-f249-4161-903b-b80d57d57ddf">

2. Jinjar and Jinja support different template syntax (jinjar is powered by the inja library), though I've tried to match things as closely as I can. This means an existing Jinja template might need some edits before it'll work with jinjar. I'd ask that you reflect this difference in your documentation (perhaps with a link to [this vignette](https://davidchall.github.io/jinjar/articles/template-syntax.html)), to avoid confusion and frustration.

**Comment by daranzolin** [comment]
Thanks for the feedback @davidchall !

1. I initially tried to pass dots `...` all the way to `jinjar_render()` via `tar_sql()` but was running into problems. I eventually settled on `params` [to mimic how params are utilized in Quarto.](https://quarto.org/docs/computations/parameters.html#knitr) Still thinking about this.
2. I will be sure to link to the above vignette, I've already referenced it several times in my own work.
