### ISSUE TITLE
Unable to use join function

### ISSUE THREAD

**Issue by castagninojose** [davidchall/jinjar#7]
Hey, thanks for this useful package :)

I think I stumbled upon an issue when trying to render a SQL query, but I may be missing a piece of the puzzle. The following snippet results in `Error: [inja.exception.parser_error] (at 3:34) unknown function join`

```{r}
library(jinjar)

sql_template <- "
    {% if isArray(cols) %}
        SELECT {{ join(cols, ', ') }}
    {% else %}
        SELECT {{ cols }}
    {% endif %}
        FROM {{ table }}
    {% if isNumber(nrows) %}
        LIMIT {{ nrows }}
    {% endif %}
"

sql <- render(sql_template, table='foo', cols="['puff', 'plaf']", nrows=10)
```

Some context (let me know if I missed something):
- `R version 4.1.3 (2022-03-10)`
- `jinjar version 0.1.0`
- `System Ubuntu 20.04`

**Comment by davidchall** [comment]
Hi José,

Unfortunately, the error message isn't very helpful in this situation. What's actually the issue is that you've tried to declare a [string literal](https://davidchall.github.io/jinjar/articles/template-syntax.html#literals) using single quotation marks (`', '`), when jinjar expects to find them using double quotation marks (`", "`). The jinjar engine can't find a `join()` function matching this signature of arguments, because it doesn't understand the second argument.

There is a second issue with how you've passed the `cols` template parameter. You need to pass this as a string vector.

``` r
library(jinjar)

sql_template <- '
    {% if isArray(cols) %}
        SELECT {{ join(cols, ", ") }}
    {% else %}
        SELECT {{ cols }}
    {% endif %}
        FROM {{ table }}
    {% if isNumber(nrows) %}
        LIMIT {{ nrows }}
    {% endif %}
'

render(sql_template, table='foo', cols=c('puff', 'plaf'), nrows=10)
#> [1] "\n    \n        SELECT puff, plaf\n    \n        FROM foo\n    \n        LIMIT 10\n    \n"
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by castagninojose** [comment]
Oh, indeed the error was a bit obscure. Thanks for the detailed response and sorry for the noise.
